name: Auto Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'   # Runs at 00:00 UTC
    - cron: '0 6 * * *'   # Runs at 06:00 UTC
    - cron: '0 12 * * *'  # Runs at 12:00 UTC
    - cron: '0 18 * * *'  # Runs at 18:00 UTC

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Modify a file (e.g., update timestamp)
        run: |
          echo "Last updated: $(date -u)" > last_updated.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_updated.txt
          git commit -m "🤖 Update - $(date -u)" || echo "Nothing to commit"
          git push
